### ISSUE TITLE
Standardize `on_pull_request` and `on_push` reusable workflows for ROCKs

### ISSUE THREAD

**Issue by orfeas-k** [canonical/charmed-kubeflow-workflows#31]
### What needs to get done

- Decide which checks we want to trigger on those events
- Create reusable workflows for each of those that will not require the repo's ROCK names as inputs. 

At the moment, we do not have standardized and explicitly decided what should happen during `on_push` and `on_pull_request`. 

#### on_pull_request
The second part is tackled by PR https://github.com/canonical/charmed-kubeflow-workflows/pull/27 which introduces `get_modified_rocks_and_build_scan_test_rock.yaml` that is designed to suffice for checks during `on_pull_request`. That's the thought also behind this implementation in [seldonio-rocks](https://github.com/canonical/seldonio-rocks/pull/64/files#diff-352263a1b21dbdaceb52c81b955c9e9de0c26fdbfb5368897ccecfeeb778502e). However, AFAIK, we haven't decided explicitly that build, scan and testing should happen during on_pull_request. This can also be observed by the fact that we have different `on_pull_request` workflows in [kubeflow-rocks](https://github.com/canonical/kubeflow-rocks/blob/main/.github/workflows/on_pull_request.yaml) and [pipelines-rocks](https://github.com/canonical/pipelines-rocks/blob/main/.github/workflows/on_pull_request.yaml) repos.

#### on_push
At the moment, there is nothing in this repo that can just be triggered as is for `on_push` events. There is the [build_and_publish_rock.yaml](https://github.com/canonical/charmed-kubeflow-workflows/blob/d2899bd683e9400289272a5b5d3d39101b5e3143/.github/workflows/build_and_publish_rock.yaml) file but cannot be called without passing arguments for each rockcraft inside a repo (as opposed to what can be done using `get_modified_rocks_and_build_scan_test_rock.yaml`. We should thus decide we expect from CI on those events.

The above should happen with the use of reusable workflows (if possible) in order to have a centralized way of controlling ROCKs CI and avoid copy-pasting the same files over many repos.

### Why it needs to get done
We need to do this in order to have centralized CI for ROCKs that will be reusable, robust and easily transferable. We will also avoid hardcoding and copy pasting stuff.

**Comment by ca-scribner** [comment]
@orfeas-k how do you envision sharing these files between repos?  Would we have something like the `get_modified_rocks_and_build_scan_test_rock.yaml` workflow in charmed-kubeflow-workflows, and then every repo has a very basic identical `on_pull_request.yaml`?  We could even have a template here for the on_pull_request.yaml maybe (**not** stored in `.github/workflows`, so it doesn't fire in this repo) and we could expect people copy and paste the file from here

**Comment by orfeas-k** [comment]
#### Sharing workflows between repos
>Would we have something like the get_modified_rocks_and_build_scan_test_rock.yaml workflow in charmed-kubeflow-workflows, and then every repo has a very basic identical on_pull_request.yaml? We could even have a template here for the on_pull_request.yaml maybe (not stored in .github/workflows, so it doesn't fire in this repo) and we could expect people copy and paste the file from here

Yes, that's how I think we should do it and this was integrated also in #27 by including [this template](https://github.com/canonical/charmed-kubeflow-workflows/pull/27/files#diff-cf2d42ed0f84274c05368d2d8ab62e34157e28d7db3b2aa26df593ec3ff88eed).

**Comment by orfeas-k** [comment]
To reiterate and close this issue, we decided the following

### `on_pull_request`

* build
* scan
* sanity test
* integration tests

### `on_push` (to `main` or `track/x.x` branches)

* build
* scan
* sanity tests
* integration tests
* push to dockerhub

This will by achieved by a common `build-scan-test-publish` workflow that will publish only when it's triggered during `push` events.
